---
# OS Debian 11
#- name: Install minimal progs # название таска
#  hosts: all # выбор груп хостов
#  tasks: # перечисление заданий
#    - name: Install sudo # именование задания
#      apt: pkg=sudo state=latest # apt(выбор пакетного менеджера) pkg(именование конкретного пакета) state(выбор конечного состояние пакета)
#    - name: Install gpg
#      apt: pkg=pgp state=latest
#    - name: Install wget
#      apt: pkg=wget state=latest
#    - name: Install GIT
#      apt: pkg=git state=latest
- name: Install Zabbix-agent
  hosts: all
  tasks:
    - name: Install zabbix-agent
      apt: pkg=zabbix-agent state=latest
#    - name: Get zabbix reload
#      ansible.builtin.systemd:
#        name: zabbix-agent
#        state: reloaded
    - name: Get zabbix enable-autostart
      ansible.builtin.systemd:
        name: zabbix-agent
        enabled: true
        masked: no
#- name: Install docker in product servers
#  host: docker-install
#  tasks:
#    - name: Install apt-transport-https
#      ansible.builtin.apt:
#        name:
#          - apt-transport-https
#          - ca-certificates
#          - gnupg
#        state: latest
#        update_cache: true
#    - name: Add signing key
#      url: "https://download.docker.com/linux/debian/gpg"
