---
# OS Debian 11
- name: Install minimal progs # название таска
  hosts: all # выбор груп хостов
  tasks: # перечисление заданий
    
    - name: Install sudo # именование задания
      apt: pkg=sudo state=latest # apt(выбор пакетного менеджера) pkg(именование конкретного пакета) state(выбор конечного состояние пакета)
    
    - name: Install gpg # именование задания
      apt: pkg=pgp state=latest
    
    - name: Install wget
      apt: pkg=wget state=latest
    
    - name: Install GIT
      apt: pkg=git state=latest
    
    - name: install curl
      apt: pkg=curl state=latest

- name: Install Zabbix-agent
  hosts: all
  tasks:

    - name: Install zabbix-agent
      apt: pkg=zabbix-agent state=latest

    - name: Get zabbix enable-autostart
      ansible.builtin.systemd:
        name: zabbix-agent
        enabled: true
        masked: no

- name: Install pre-reqs for Docker and Ansible
  hosts: docker-install
  tasks:

      - name: install apt-transport-https
        apt: pkg=apt-transport-https state=latest
     
      - name: install ca-certificates
        apt: pkg=ca-certificates
     
      - name: install software-properties-common
        apt: pkg=software-properties-common
     
      - name: Install python3-pip
        apt: pkg=python3-pip state=latest
     
      - name: Install virtualenv
        apt: pkg=virtualenv state=latest
     
      - name: Install python3-setuptools
        apt: pkg=python3-setuptools state=latest
     
      - name: Add the GPG key for Docker 
        shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor | tee /usr/share/keyrings/docker-archive-keyring.gpg'

      - name: Add the repository to fetch the docker package
        shell: 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable" | tee /etc/apt/sources.list.d/docker.list'

      - name: Update source list and then install docker
        apt: update_cache=yes name=docker-ce state=latest

      - name: Install the Docker module for Python, required by ansible
        pip:
          name: docker

- name: install nginx on boreder machine
  hosts: nginx-revers-proxy
  tasks:

      - name: install nginx
        apt: pkg=nginx state=latest
      
      - name: Get zabbix enable-autostart
        ansible.builtin.systemd:
          name: nginx
          enabled: true
          masked: no
